[ -f ~/.shellrc ] && source ~/.shellrc

[ -f ~/.config/shell/bash_sensible ] && source ~/.config/shell/.bash_sensible

[ -f /usr/local/etc/profile.d/bash-preexec.sh ] && . /usr/local/etc/profile.d/bash-preexec.sh

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

eval "$(starship init bash)"
eval "$(zoxide init bash)"
eval "$(atuin init bash)"

[ -f ~/.config/shell/fzf.bash ] && source ~/.config/shell/.fzf.bash
