[ -f ~/.shellrc ] && source ~/.shellrc

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
  compaudit | xargs chmod go-w
fi

eval "$(atuin init zsh)"

[ -f ~/.config/shell/.fzf.zsh ] && source ~/.config/shell/.fzf.zsh

eval "$(starship init zsh)"

[ -f ~/.config/shell/zsh_plugins ] && source ~/.config/shell/.zsh_plugins
