[ -f ~/.shellrc ] && source ~/.shellrc

[ -f ~/.config/shell/.zsh_plugins ] && source ~/.config/shell/.zsh_plugins

HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTFILE=~/.zsh_history
HISTDUP=erase

setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_save_no_dups
setopt hist_find_no_dups

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors '${(s.:.)LS_COLORS}'
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'exa --color $realpath'

autoload -U compinit && compinit
zinit cdreplay -q

eval "$(starship init zsh)"
eval "$(atuin init zsh)"
eval "$(zoxide init zsh --no-cmd)"

[ -f ~/.config/shell/.fzf.zsh ] && source ~/.config/shell/.fzf.zsh
