[ -f ~/.shellrc ] && source ~/.shellrc

[ -f ~/.bash_sensible ] && source ~/.bash_sensible

[ -f /usr/local/etc/profile.d/bash-preexec.sh ] && . /usr/local/etc/profile.d/bash-preexec.sh

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

eval "$(atuin init bash)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

eval "$(starship init bash)"
